services:
  db:
    image: postgres:alpine
    container_name: learning_chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    networks:
      - app-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      sh -c "apk add --no-cache musl-locales &&
            apk add --no-cache tzdata &&
            ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime &&
            exec docker-entrypoint.sh postgres"

  pgadmin:
    image: dpage/pgadmin4
    container_name: learning_chat_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin   # Логин для доступа к pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin            # Пароль для доступа к pgAdmin
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - db    

  redis:
    image: redis:alpine
    container_name: learning_chat_redis
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: app-network
    driver: bridge